server:
  port: 8080

spring:
  application:
    name: rock-paper-scissor-main-service

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true